-- ============================================================================
-- Exercise 2: Error Handling
-- ============================================================================
SET SERVEROUTPUT ON;

-- Error log table (create once). Requires Oracle 12c+ for IDENTITY.
CREATE TABLE Error_Log (
    ErrorID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ErrorMsg  VARCHAR2(400),
    ErrorDate DATE DEFAULT SYSDATE
);

-- ----------------------------------------------------------------------------
-- Scenario 1: SafeTransferFunds - transfer with rollback + error logging.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SafeTransferFunds (
    p_from_acc IN NUMBER,
    p_to_acc   IN NUMBER,
    p_amount   IN NUMBER
) IS
    v_balance NUMBER;
BEGIN
    SELECT Balance INTO v_balance
    FROM   Accounts
    WHERE  AccountID = p_from_acc
    FOR UPDATE;

    IF v_balance < p_amount THEN
        RAISE_APPLICATION_ERROR(-20001, 'Insufficient funds in account ' || p_from_acc);
    END IF;

    UPDATE Accounts SET Balance = Balance - p_amount WHERE AccountID = p_from_acc;
    UPDATE Accounts SET Balance = Balance + p_amount WHERE AccountID = p_to_acc;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Transfer of ' || p_amount || ' successful.');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        ROLLBACK;
        INSERT INTO Error_Log(ErrorMsg) VALUES ('SafeTransferFunds: invalid source account ' || p_from_acc);
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Error: invalid source account.');
    WHEN OTHERS THEN
        ROLLBACK;
        INSERT INTO Error_Log(ErrorMsg) VALUES ('SafeTransferFunds: ' || SQLERRM);
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;
/

-- ----------------------------------------------------------------------------
-- Scenario 2: UpdateSalary - raise salary by a % ; log if employee not found.
-- (UPDATE does not raise NO_DATA_FOUND, so SQL%ROWCOUNT is checked explicitly.)
-- ----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE UpdateSalary (
    p_emp_id IN NUMBER,
    p_pct    IN NUMBER
) IS
BEGIN
    UPDATE Employees
    SET    Salary = Salary + (Salary * p_pct / 100)
    WHERE  EmployeeID = p_emp_id;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE NO_DATA_FOUND;
    END IF;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Salary updated for employee ' || p_emp_id);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        INSERT INTO Error_Log(ErrorMsg) VALUES ('UpdateSalary: EmployeeID ' || p_emp_id || ' not found.');
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Error: Employee ' || p_emp_id || ' not found.');
    WHEN OTHERS THEN
        ROLLBACK;
        INSERT INTO Error_Log(ErrorMsg) VALUES ('UpdateSalary: ' || SQLERRM);
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;
/

-- ----------------------------------------------------------------------------
-- Scenario 3: AddNewCustomer - insert; block duplicates via DUP_VAL_ON_INDEX.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE AddNewCustomer (
    p_id      IN NUMBER,
    p_name    IN VARCHAR2,
    p_dob     IN DATE,
    p_balance IN NUMBER
) IS
BEGIN
    INSERT INTO Customers(CustomerID, Name, DOB, Balance, LastModified)
    VALUES (p_id, p_name, p_dob, p_balance, SYSDATE);

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Customer ' || p_id || ' added.');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        INSERT INTO Error_Log(ErrorMsg) VALUES ('AddNewCustomer: duplicate CustomerID ' || p_id);
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Error: Customer ' || p_id || ' already exists.');
    WHEN OTHERS THEN
        ROLLBACK;
        INSERT INTO Error_Log(ErrorMsg) VALUES ('AddNewCustomer: ' || SQLERRM);
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;
/

-- ---- Demonstration ---------------------------------------------------------
BEGIN
    SafeTransferFunds(1, 2, 999999);          -- insufficient funds
    UpdateSalary(9999, 10);                    -- employee not found
    AddNewCustomer(1, 'John Doe', SYSDATE, 0); -- duplicate id
END;
/