-- ============================================================================
-- Exercise 5: Triggers
-- ============================================================================
SET SERVEROUTPUT ON;

-- ----------------------------------------------------------------------------
-- Scenario 1: UpdateCustomerLastModified - stamp LastModified on any update.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER UpdateCustomerLastModified
BEFORE UPDATE ON Customers
FOR EACH ROW
BEGIN
    :NEW.LastModified := SYSDATE;
END;
/

-- ----------------------------------------------------------------------------
-- Scenario 2: LogTransaction - audit every inserted transaction.
-- ----------------------------------------------------------------------------
-- Audit table (create once). Requires Oracle 12c+ for IDENTITY.
CREATE TABLE AuditLog (
    AuditID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TransactionID   NUMBER,
    AccountID       NUMBER,
    Amount          NUMBER,
    TransactionType VARCHAR2(10),
    AuditDate       DATE DEFAULT SYSDATE
);

CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog(TransactionID, AccountID, Amount, TransactionType, AuditDate)
    VALUES (:NEW.TransactionID, :NEW.AccountID, :NEW.Amount, :NEW.TransactionType, SYSDATE);
END;
/

-- ----------------------------------------------------------------------------
-- Scenario 3: CheckTransactionRules - deposits positive; withdrawals <= balance.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER CheckTransactionRules
BEFORE INSERT ON Transactions
FOR EACH ROW
DECLARE
    v_balance NUMBER;
BEGIN
    IF :NEW.Amount <= 0 THEN
        RAISE_APPLICATION_ERROR(-20010, 'Transaction amount must be positive.');
    END IF;

    IF UPPER(:NEW.TransactionType) = 'WITHDRAWAL' THEN
        SELECT Balance INTO v_balance
        FROM   Accounts
        WHERE  AccountID = :NEW.AccountID;

        IF :NEW.Amount > v_balance THEN
            RAISE_APPLICATION_ERROR(-20011, 'Withdrawal exceeds available balance.');
        END IF;
    END IF;
END;
/